:: run this batch file from the MUSES Open Source Software directory
:: make sure you are running Python 3.8 or higher, and have installed the package dependencies listed in requirements.txt

cd "MUSES Open Source Software Code/preprocessing"
python preprocessing.py --functionality=clean_data --input_file=../data/synthetic_data/synthetic_data_2021.csv --sep="," --attributes_in_sequence="date time hospcode agegroup cc" --search_group_attributes="hospcode agegroup" --search_group_file_names="../data/synthetic_data/Settings/single_hospcode_searchgroups.csv ../data/synthetic_data/Settings/age_search_groups_all.csv" --icd_map_file="./dicts/icd9_to_text_list.txt" --start_date="01/01/2021 00:00" --end_date="12/31/2021 23:59" --chunksize=100000 --correcting_misspell="./dicts/correct_common_mistakes_list.txt" --remove_word_list="./dicts/remove_word_list.txt" --output_file_name="../data/synthetic_data/processed_2021.csv" --output_all_search_groups="../data/synthetic_data/sg_full.csv" --output_sg_dict="../data/synthetic_data/sg_dict_full.pickle" --output_word_index_dict_file="../data/synthetic_data/word_dict_2021.txt" --word_index_load_file=""
python preprocessing.py --functionality=clean_data --input_file=../data/synthetic_data/synthetic_data_Jan_2022.csv --sep="," --attributes_in_sequence="date time hospcode agegroup cc" --search_group_attributes="hospcode agegroup" --search_group_file_names="../data/synthetic_data/Settings/single_hospcode_searchgroups.csv ../data/synthetic_data/Settings/age_search_groups_all.csv" --icd_map_file="./dicts/icd9_to_text_list.txt" --start_date="01/01/2022 00:00" --end_date="01/31/2022 23:59" --chunksize=100000 --correcting_misspell="./dicts/correct_common_mistakes_list.txt" --remove_word_list="./dicts/remove_word_list.txt" --output_file_name="../data/synthetic_data/processed_Jan_2022.csv" --output_all_search_groups="" --output_sg_dict="" --output_word_index_dict_file="../data/synthetic_data/word_dict_full.txt" --word_index_load_file="../data/synthetic_data/word_dict_2021.txt"
cd ../topic_modeling
python train_background.py --data_file="../data/synthetic_data/processed_2021.csv" --dict_file="../data/synthetic_data/word_dict_full.txt" --num_static_topics=25 --static_iters=3000 --verbose=100 --checkpoint="../data/synthetic_data/checkpoint/static_2021_25topics.npz"
python semantic_scan.py --full_scan_file="../data/synthetic_data/processed_Jan_2022.csv" --dict_file="../data/synthetic_data/word_dict_full.txt" --sg_dict="../data/synthetic_data/sg_dict_full.pickle" --sg_list="../data/synthetic_data/sg_full.csv" --static_checkpoint="../data/synthetic_data/checkpoint/static_2021_25topics.npz" --import_monitored="" --num_foreground_topics=25 --static_iters=1000 --contrastive_iters=1000 --verbose=False --step_size=1 --window_size=3 --baseline_size=21 --score_threshold=4.0 --start_date="2022/01/29" --end_date="2022/01/31" --topic_weight=False --cluster_dir="../data/synthetic_data/clusters" --concatenate_agegroup=True
cd ../visualization
python visualize.py --results_folder="../data/synthetic_data/clusters" --monitored_topic_file="../data/synthetic_data/monitored_topics.csv"
